spring:
  application:
    name: service-system
  profiles:
    active: pro
  # 约束文件上传大小
  servlet.multipart.max-file-size: 10MB
  servlet.multipart.max-request-size: 100MB

logging.level.org.springframework.mail: DEBUG
logging.level.org.springframework.boot.autoconfigure.mail: DEBUG

jwt:
  # 设置jwt签名加密时使用的秘钥
  secret-key: Iceuu
  # 设置jwt过期时间
  ttl: 259200000
  # 设置前端传递过来的令牌名称
  token-name: Authorization

# API文档配置
knife4j:
  enable: true

  # 自定义主页内容
  openapi:
    title: ThriveX 在线API文档
    description: 有些梦虽然遥不可及，但并不是不可能实现!
    email:  1873048956@qq.com
    concat: 小冷
    url: https://liuyuyang.net
    version: v4.0
    license: Apache 2.0
    terms-of-service-url: https://stackoverflow.com/

    # 分组
    group:
      default:
        group-name: default
        api-rule: package
        api-rule-resources:
          - liuyuyang.net

  # 自定义页脚内容
  setting:
    enable-footer: false
    enable-footer-custom: true
    footer-custom-content: 互联网从不缺乏天才，而努力才是最终的入场劵!

dromara:
  # 文件存储配置
  x-file-storage:
    default-platform: local-plus
    local-plus:
      - platform: local # 存储平台标识
        enable-storage: true  # 启用存储
        enable-access: true # 启用访问（线上请使用 Nginx 配置，效率更高）
        path-patterns: /static/** # 访问路径

file:
  dir: ./upload/

server:
  tomcat:
    uri-encoding: UTF-8
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  messages:
    encoding: UTF-8

